# Generated by Django 5.0.1 on 2024-01-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardlist',
            old_name='list_type',
            new_name='type',
        ),
    ]
