# Generated by Django 5.0.1 on 2024-01-20 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_list_type_cardlist_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='YugiohCard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=100)),
                ('frame_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('level', models.IntegerField()),
                ('race', models.CharField(max_length=100)),
                ('attribute', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=255)),
                ('set_code', models.CharField(max_length=100)),
                ('set_rarity', models.CharField(max_length=100)),
                ('set_rarity_code', models.CharField(max_length=100)),
                ('set_price', models.CharField(max_length=100)),
                ('yugioh_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sets', to='api.yugiohcard')),
            ],
        ),
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardmarket_price', models.CharField(max_length=100)),
                ('tcgplayer_price', models.CharField(max_length=100)),
                ('ebay_price', models.CharField(max_length=100)),
                ('amazon_price', models.CharField(max_length=100)),
                ('coolstuffinc_price', models.CharField(max_length=100)),
                ('yugioh_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_prices', to='api.yugiohcard')),
            ],
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image_url_small', models.URLField()),
                ('image_url_cropped', models.URLField()),
                ('yugioh_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_images', to='api.yugiohcard')),
            ],
        ),
    ]
