# Generated by Django 5.0.1 on 2024-01-20 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_yugiohcard_cardset_cardprice_cardimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.JSONField()),
                ('convertedEnergyCost', models.IntegerField()),
                ('damage', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonCardSet',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('series', models.CharField(max_length=200)),
                ('printedTotal', models.IntegerField()),
                ('total', models.IntegerField()),
                ('legalities', models.JSONField()),
                ('ptcgoCode', models.CharField(max_length=100)),
                ('releaseDate', models.DateField()),
                ('updatedAt', models.DateTimeField()),
                ('symbol', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonCardData',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('supertype', models.CharField(max_length=100)),
                ('subtypes', models.JSONField()),
                ('level', models.CharField(max_length=50)),
                ('hp', models.CharField(max_length=50)),
                ('types', models.JSONField()),
                ('retreatCost', models.JSONField()),
                ('convertedRetreatCost', models.IntegerField()),
                ('number', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=200)),
                ('rarity', models.CharField(max_length=100)),
                ('flavorText', models.TextField()),
                ('nationalPokedexNumbers', models.JSONField()),
                ('legalities', models.JSONField()),
                ('images', models.JSONField()),
                ('tcgplayer', models.JSONField(blank=True, null=True)),
                ('cardmarket', models.JSONField(blank=True, null=True)),
                ('attacks', models.ManyToManyField(to='api.pokemonattack')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cardset')),
                ('weaknesses', models.ManyToManyField(to='api.pokemonweakness')),
            ],
        ),
    ]
