# Generated by Django 5.0.1 on 2024-01-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pokemoncarddata_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncardset',
            name='releaseDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemoncardset',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
