# Generated by Django 5.0.1 on 2024-01-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_pokemoncarddata_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonattack',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
