# Generated by Django 5.0.1 on 2024-01-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_pokemonattack_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='LorcanaCardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('set_name', models.CharField(max_length=200)),
                ('set_num', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('cost', models.PositiveIntegerField()),
                ('inkable', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=100)),
                ('flavor_text', models.TextField(blank=True)),
                ('card_num', models.PositiveIntegerField()),
                ('body_text', models.TextField(blank=True)),
                ('set_id', models.CharField(max_length=200)),
            ],
        ),
    ]
