# Generated by Django 5.0.1 on 2024-01-20 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_lorcanacarddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTGCardsData',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('oracle_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('lang', models.CharField(max_length=2)),
                ('released_at', models.DateField()),
                ('uri', models.URLField()),
                ('layout', models.CharField(max_length=100)),
                ('image_uris', models.JSONField(blank=True, null=True)),
                ('cmc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type_line', models.CharField(max_length=200)),
                ('color_identity', models.JSONField()),
                ('keywords', models.JSONField()),
                ('legalities', models.JSONField()),
                ('games', models.JSONField()),
                ('set', models.CharField(max_length=50)),
                ('set_name', models.CharField(max_length=200)),
                ('set_type', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=200)),
                ('prices', models.JSONField()),
                ('related_uris', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MTGRelatedCard',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('component', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('type_line', models.CharField(max_length=200)),
                ('uri', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MTGCardFace',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('oracle_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('mana_cost', models.CharField(max_length=100)),
                ('type_line', models.CharField(max_length=200)),
                ('oracle_text', models.TextField()),
                ('colors', models.JSONField()),
                ('power', models.CharField(max_length=10)),
                ('toughness', models.CharField(max_length=10)),
                ('artist', models.CharField(max_length=200)),
                ('image_uris', models.JSONField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_faces', to='api.mtgcardsdata')),
            ],
        ),
        migrations.AddField(
            model_name='mtgcardsdata',
            name='all_parts',
            field=models.ManyToManyField(blank=True, to='api.mtgrelatedcard'),
        ),
    ]
