# Generated by Django 5.0.1 on 2024-01-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_mtgcardface_oracle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtgcardsdata',
            name='cmc',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
