# Generated by Django 5.0.1 on 2024-01-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_mtgcardsdata_cmc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemoncarddata',
            name='attacks',
        ),
        migrations.RemoveField(
            model_name='pokemoncarddata',
            name='set',
        ),
        migrations.RemoveField(
            model_name='pokemoncarddata',
            name='weaknesses',
        ),
        migrations.DeleteModel(
            name='PokemonAttack',
        ),
        migrations.DeleteModel(
            name='PokemonCardSet',
        ),
        migrations.DeleteModel(
            name='PokemonCardData',
        ),
        migrations.DeleteModel(
            name='PokemonWeakness',
        ),
    ]
