# Generated by Django 5.0.1 on 2024-01-20 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_pokemoncarddata_attacks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.JSONField()),
                ('convertedEnergyCost', models.IntegerField()),
                ('damage', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonCardmarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('updatedAt', models.DateTimeField()),
                ('prices', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonCardSet',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('series', models.CharField(max_length=200)),
                ('printedTotal', models.IntegerField()),
                ('total', models.IntegerField()),
                ('legalities', models.JSONField()),
                ('ptcgoCode', models.CharField(max_length=100)),
                ('releaseDate', models.DateField()),
                ('updatedAt', models.DateTimeField()),
                ('images', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonTcgplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('updatedAt', models.DateTimeField()),
                ('prices', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonCardData',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('supertype', models.CharField(max_length=100)),
                ('subtypes', models.JSONField()),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('hp', models.CharField(max_length=50)),
                ('types', models.JSONField()),
                ('evolvesFrom', models.CharField(blank=True, max_length=200, null=True)),
                ('retreatCost', models.JSONField()),
                ('convertedRetreatCost', models.IntegerField()),
                ('number', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=200)),
                ('rarity', models.CharField(max_length=100)),
                ('flavorText', models.TextField(blank=True, null=True)),
                ('nationalPokedexNumbers', models.JSONField()),
                ('legalities', models.JSONField()),
                ('images', models.JSONField()),
                ('abilities', models.ManyToManyField(blank=True, to='api.pokemonability')),
                ('attacks', models.ManyToManyField(to='api.pokemonattack')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cardset')),
                ('cardmarket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pokemoncardmarket')),
                ('tcgplayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pokemontcgplayer')),
                ('weaknesses', models.ManyToManyField(to='api.pokemonweakness')),
            ],
        ),
    ]
