# Generated by Django 5.0.1 on 2024-01-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_pokemonability_pokemonattack_pokemoncardmarket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncardset',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
