# Generated by Django 5.0.1 on 2024-01-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_pokemoncardset_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncardmarket',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemontcgplayer',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
