# Generated by Django 5.0.1 on 2024-01-20 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_pokemoncardmarket_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncarddata',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pokemoncardset'),
        ),
    ]
