# Generated by Django 5.0.1 on 2024-01-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_pokemoncarddata_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonattack',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
