# Generated by Django 5.0.1 on 2024-01-21 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_pokemoncarddata_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_cards', to='api.cardlist')),
                ('pokemon_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pokemoncarddata')),
                ('yugioh_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.yugiohcard')),
            ],
        ),
    ]
