# Generated by Django 5.0.1 on 2024-01-22 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_listcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcard',
            name='lorcana_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lorcanacarddata'),
        ),
        migrations.AddField(
            model_name='listcard',
            name='mtg_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mtgcardsdata'),
        ),
    ]
