# Generated by Django 5.0.1 on 2024-01-22 23:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_listcard_lorcana_card_listcard_mtg_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcard',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
