# Generated by Django 5.0.1 on 2024-01-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_listcard_market_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtgcardsdata',
            name='prices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
