# Generated by Django 5.0.1 on 2024-01-29 21:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_mtgcardsdata_cmc_alter_mtgcardsdata_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlist',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
