# Generated by Django 5.0.1 on 2024-02-03 17:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_listcard_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlist',
            name='collection_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
