# Generated by Django 5.0.1 on 2024-02-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_cardlist_collection_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlist',
            name='needs_update',
            field=models.BooleanField(default=False),
        ),
    ]
