# Generated by Django 5.1.1 on 2024-09-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_cardlist_needs_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="listcard",
            name="card_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
